In [ ]:
import pandas as pd

In [3]:
DATA_PATH = "../data/raw/Dataset- Superstore (2015-2018).csv"

df = pd.read_csv(DATA_PATH)

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016/11/08,2016/11/11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016/11/08,2016/11/11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016/06/12,2016/06/16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015/10/11,2015/10/18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015/10/11,2015/10/18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.shape

(9994, 21)

In [5]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [7]:
df.isna().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [10]:
df[["Ship Mode", "Segment", "Region", "Category"]].nunique()

Ship Mode    4
Segment      3
Region       4
Category     3
dtype: int64

In [11]:
for col in ["Ship Mode", "Segment", "Region", "Category"]:
    print(f"\n{col}:")
    print(df[col].unique())

Ship Mode:
<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

Segment:
<StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

Region:
<StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

Category:
<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

In [12]:
pd.to_datetime(df["Order Date"], errors="coerce").isna().sum()

np.int64(0)

In [13]:
pd.to_datetime(df["Ship Date"], errors="coerce").isna().sum()

np.int64(0)

In [14]:
order_date = pd.to_datetime(df["Order Date"])
ship_date = pd.to_datetime(df["Ship Date"])

(ship_date < order_date).sum()

np.int64(0)

In [15]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [16]:
df[["Order Date", "Ship Date"]].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [17]:
df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

df["Shipping Days"].describe()

count    9994.000000
mean        3.958175
std         1.747567
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Shipping Days, dtype: float64

In [18]:
df["Shipping Days"].value_counts().sort_index()

Shipping Days
0     519
1     369
2    1334
3    1005
4    2774
5    2169
6    1203
7     621
Name: count, dtype: int64

In [19]:
df.groupby("Ship Mode")["Shipping Days"].agg(
    ["count", "mean", "min", "max"]
).sort_values("mean")

                count      mean  min  max
Ship Mode
Same Day          543  0.044199    0    1
First Class      1538  2.182705    1    4
Second Class     1945  3.238046    1    5
Standard Class   5968  5.006535    3    7

In [21]:
df["Order ID"].duplicated().sum()

np.int64(4985)

In [22]:
print("Unique Orders:", df["Order ID"].nunique())
print("Unique Customers:", df["Customer ID"].nunique())
print("Unique Products:", df["Product ID"].nunique())

Unique Orders: 5009
Unique Customers: 793
Unique Products: 1862

In [23]:
order_sales = df.groupby("Order ID")["Sales"].sum()

order_sales.mean()

np.float64(458.61466566180883)

In [24]:
print("Total Sales:", df["Sales"].sum())
print("Total Profit:", df["Profit"].sum())
print("Total Quantity:", df["Quantity"].sum())

Total Sales: 2297200.8603
Total Profit: 286397.0217
Total Quantity: 37873

In [25]:
profit_margin = df["Profit"].sum() / df["Sales"].sum() * 100

print("Overall Profit Margin:", profit_margin, "%")

Overall Profit Margin: 12.467217240315605 %

In [26]:
df["Row ID"].nunique()

9994

In [27]:
print("Sales <= 0:", (df["Sales"] <= 0).sum())
print("Quantity <= 0:", (df["Quantity"] <= 0).sum())
print("Discount outside 0-1:", ((df["Discount"] < 0) | (df["Discount"] > 1)).sum())

Sales <= 0: 0
Quantity <= 0: 0
Discount outside 0-1: 0

In [28]:
print("Order Date:", df["Order Date"].min(), "to", df["Order Date"].max())
print("Ship Date:", df["Ship Date"].min(), "to", df["Ship Date"].max())

Order Date: 2014-01-03 00:00:00 to 2017-12-30 00:00:00
Ship Date: 2014-01-07 00:00:00 to 2018-01-05 00:00:00

In [29]:
print("Loss-making rows:", (df["Profit"] < 0).sum())
print("Loss-making %:", (df["Profit"] < 0).mean() * 100)

Loss-making rows: 1871
Loss-making %: 18.721232739643785

In [30]:
order_consistency = df.groupby("Order ID").agg(
    unique_customers=("Customer ID", "nunique"),
    unique_order_dates=("Order Date", "nunique")
)

print(
    "Orders with multiple customers:",
    (order_consistency["unique_customers"] > 1).sum()
)

print(
    "Orders with multiple order dates:",
    (order_consistency["unique_order_dates"] > 1).sum()
)

Orders with multiple customers: 0
Orders with multiple order dates: 0